apiVersion: v2
name: wslvpn
description: WSL Zero Trust VPN control plane
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/bwalia/wslvpn
sources:
  - https://github.com/bwalia/wslvpn
maintainers:
  - name: WSL Zero Trust VPN Contributors
